// Part 18: API keys (machine credentials for the public REST API).
//
// Per Plan Part 18: "Store only hashes for API keys ...". Per Notted.md "API
// Keys": workspace admins create scoped API keys; the full key is shown ONCE on
// creation and is never retrievable afterward; the key prefix is shown in the
// UI for identification; keys can be revoked instantly. Per ADR 0003: "Public
// API keys are a separate machine-credential type owned by Notted, stored only
// as hashes and bound to one workspace and explicit scopes."
//
// HASH-ONLY MODEL (CRITICAL):
// - `key_hash` stores a salted hash (e.g. argon2/scrypt of the random secret,
//   or SHA-256 of the secret over a fixed pepper) generated by the API-key
//   service (Part 61). The RAW KEY IS NEVER PERSISTED, never logged, never
//   returned after the creation response. The full key exists only in the HTTP
//   response of the create call and in the caller's secret store.
// - `key_prefix` is the only human-visible fragment (e.g. "ntd_pk_a" → the
//   first 8 chars). It lets admins identify which key made a request in logs
//   and the UI list WITHOUT revealing the secret. The service (Part 61)
//   generates a prefix at creation; it is NOT sensitive on its own (it cannot
//   authenticate) but is treated as display metadata.
// - `key_hash` is UNIQUE: each generated secret maps to exactly one row, and
//   the lookup path (authenticate-by-API-key) is a single unique-index scan on
//   the hash of the presented secret.
//
// SCOPES MODEL: `scopes` is a comma-separated varchar (default "read,write"),
// matching the Notted.md sample. The allowed scope tokens are `read`, `write`,
// and `admin` (Notted.md "Scoped permissions: read, write, admin"). The
// API-key service (Part 61) parses the CSV, rejects unknown tokens, and
// enforces scope on every authenticated request. A jsonb array was considered
// and rejected: the CSV matches the Notted.md sample, keeps the column
// compact, and is trivially queryable with `like`/string-functions when
// needed; the service is the single parser so the on-disk shape stays simple.
//
// LIFECYCLE:
// - `last_used_at` is updated by the API-key auth middleware (Part 61) on each
//   successful authentication; it is informational, not security-critical.
// - `expires_at` is optional (NULL = no expiry). The service rejects expired
//   keys at authentication.
// - `is_revoked` is the instant-revocation flag (Notted.md "Revoke keys
//   instantly"). Revocation is a soft flag rather than a row delete so the
//   audit trail and prefix identification survive revocation.
//
// Deletion model:
// - `workspace_id` CASCADE: deleting a workspace removes its API keys.
// - `created_by_id` RESTRICT: deleting the admin who created a key must not
//   silently drop the credential audit; the service (Part 26) reassigns or
//   revokes before the creator account can be removed (Part 14/15/16/17 audit
//   convention).
//
// Conventions (copied from Part 13–17): see `note-embeddings.ts` module
// comment.

import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { users } from "./users";
import { workspaces } from "./workspaces";

// --------------------------------------------------------------------------- //
// api_keys
// --------------------------------------------------------------------------- //

export const apiKeys = pgTable(
  "api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .references(() => workspaces.id, { onDelete: "cascade" })
      .notNull(),
    // Admin who created the key. RESTRICT (audit convention — see module
    // comment); the service reassigns/revokes before account deletion.
    createdById: uuid("created_by_id")
      .references(() => users.id, { onDelete: "restrict" })
      .notNull(),
    // Human-readable label for the UI list (e.g. "CI export runner").
    name: varchar("name", { length: 100 }).notNull(),
    // HASH ONLY. Salted hash of the raw secret (Part 61). UNIQUE so the
    // authenticate-by-key lookup is one index scan and a duplicate secret is
    // impossible. The raw key is NEVER stored, logged, or returned post-create.
    keyHash: varchar("key_hash", { length: 255 }).notNull(),
    // Display prefix (first ~8 chars of the raw key). Non-sensitive on its own
    // (cannot authenticate); shown in the UI so admins can identify the key.
    keyPrefix: varchar("key_prefix", { length: 8 }).notNull(),
    // Comma-separated scope tokens (default "read,write"). Allowed tokens:
    // read, write, admin (Notted.md). The service parses/validates; see module
    // comment for the CSV-vs-jsonb trade-off.
    scopes: varchar("scopes", { length: 255 }).default("read,write").notNull(),
    // Informational: set by the auth middleware on each successful use.
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    // Optional expiry. NULL = no expiry. The service rejects expired keys.
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    // Instant-revocation flag. Soft flag so the audit trail survives
    // revocation (the row is retained; `is_revoked` blocks authentication).
    isRevoked: boolean("is_revoked").default(false).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    // UNIQUE key_hash: lookup + uniqueness for the authenticate-by-key path.
    uniqueIndex("api_keys_key_hash_unique").on(t.keyHash),
    // "List API keys for workspace X" admin view.
    index("api_keys_workspace_id_idx").on(t.workspaceId),
  ],
);

// --------------------------------------------------------------------------- //
// Relations
// --------------------------------------------------------------------------- //
// Forward relations only; `workspacesRelations` and `usersRelations` are not
// extended, to keep earlier parts immutable per the handoff rules.

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  workspace: one(workspaces, {
    fields: [apiKeys.workspaceId],
    references: [workspaces.id],
  }),
  createdBy: one(users, {
    fields: [apiKeys.createdById],
    references: [users.id],
    relationName: "api_keys_createdBy",
  }),
}));
