// Part 16: tags and note_tags — workspace-scoped labels and their junction.
//
// Tags are flat workspace-scoped labels (NOT a tree, NOT a project). Per Plan
// Part 16: unique workspace tag names, composite primary keys for junction
// rows. A tag NAME is unique within its workspace (`tags_workspace_name_
// unique`); the same name may exist in another workspace. Tags carry NO
// creator audit column in the brief/task spec — they are workspace-level
// resources, not personal authored entities — so unlike notes/projects/
// comments there is no `created_by_id` here.
//
// `note_tags` is a pure junction table with a COMPOSITE PRIMARY KEY on
// `(note_id, tag_id)` and NO synthetic `id` column (Plan Part 16: "composite
// primary keys for junction rows"). The composite PK also acts as the
// uniqueness guarantee: a duplicate `(note_id, tag_id)` assignment is rejected
// with SQLSTATE 23505 by the PK index, so no separate unique index is needed.
// Both FKs CASCADE: deleting a note removes its tag assignments; deleting a
// tag removes its assignments across notes. Neither side is "owner" of the
// edge — the edge exists only while both endpoints exist.
//
// Cross-tenant integrity: `tags.workspace_id` scopes a tag to its workspace.
// `note_tags` does NOT carry `workspace_id` itself; it reaches the workspace
// transitively via `note_id` -> `notes.workspace_id` and via `tag_id` ->
// `tags.workspace_id`. A cross-workspace assignment (a tag from workspace A
// applied to a note in workspace B) is therefore a two-hop invariant that the
// service (Part 24/31) enforces in the assign-transaction; it is NOT
// expressible as a single-column DB constraint without denormalizing
// `workspace_id` onto the junction, which the brief deliberately omits.
//
// Conventions (copied from Part 13/14/15): see `projects.ts` module comment.
// `primaryKey` (composite) is imported from `"drizzle-orm/pg-core"`.

import { relations } from "drizzle-orm";
import {
  index,
  pgTable,
  primaryKey,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { notes } from "./notes";
import { workspaces } from "./workspaces";

// --------------------------------------------------------------------------- //
// tags
// --------------------------------------------------------------------------- //

export const tags = pgTable(
  "tags",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .references(() => workspaces.id, { onDelete: "cascade" })
      .notNull(),
    // Tag label. Unique within the workspace via `tags_workspace_name_unique`.
    // Case-sensitivity follows PostgreSQL's default collation (treated as
    // distinct); case-insensitive uniqueness is service-side if required.
    name: varchar("name", { length: 50 }).notNull(),
    // Hex accent color. The service (Part 40+) validates the `#rrggbb` shape;
    // the column only constrains length. Default neutral gray.
    color: varchar("color", { length: 7 }).default("#6b7280"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    // Unique workspace tag names (Plan Part 16). The pair (workspace_id, name)
    // is unique; the same name may exist in another workspace.
    uniqueIndex("tags_workspace_name_unique").on(t.workspaceId, t.name),
    // "List tags in workspace" hot path.
    index("tags_workspace_id_idx").on(t.workspaceId),
  ],
);

// --------------------------------------------------------------------------- //
// note_tags (junction)
// --------------------------------------------------------------------------- //
// Composite PK on (note_id, tag_id); NO synthetic id. The composite PK index
// also enforces pair uniqueness, so a duplicate assignment is rejected with
// 23505. An additional single-column index on `tag_id` serves the "notes with
// tag X" reverse lookup; the composite PK's leftmost prefix already covers the
// "tags on note X" forward lookup, so no separate `note_id` index is added.

export const noteTags = pgTable(
  "note_tags",
  {
    noteId: uuid("note_id")
      .references(() => notes.id, { onDelete: "cascade" })
      .notNull(),
    tagId: uuid("tag_id")
      .references(() => tags.id, { onDelete: "cascade" })
      .notNull(),
  },
  (t) => [
    // Composite primary key. Acts as the uniqueness guarantee for the
    // (note, tag) pair — no separate unique index. Name is auto-generated by
    // Drizzle/PostgreSQL.
    primaryKey({ columns: [t.noteId, t.tagId] }),
    // "Notes with tag X" reverse lookup (the PK's leftmost prefix is note_id,
    // which covers the forward "tags on note X" lookup).
    index("note_tags_tag_id_idx").on(t.tagId),
  ],
);

// --------------------------------------------------------------------------- //
// Relations
// --------------------------------------------------------------------------- //
// Forward relations only; `workspacesRelations` and `notesRelations` are not
// extended here, to keep Part 13/14/15 files immutable per the handoff rules.

export const tagsRelations = relations(tags, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [tags.workspaceId],
    references: [workspaces.id],
  }),
  noteTags: many(noteTags),
}));

export const noteTagsRelations = relations(noteTags, ({ one }) => ({
  note: one(notes, {
    fields: [noteTags.noteId],
    references: [notes.id],
  }),
  tag: one(tags, {
    fields: [noteTags.tagId],
    references: [tags.id],
  }),
}));
