/**
 * Stable public barrel for cross-boundary Zod schemas and inferred inputs.
 *
 * Import consumers from `@notted/shared-validators`, never package internals.
 */

export {
  authPasswordSchema,
  createUserProfileSchema,
  oauthProviderIdSchema,
  passkeyNameSchema,
  reauthenticateSchema,
  recoveryCodeSchema,
  registerWithPasswordSchema,
  requestEmailVerificationSchema,
  requestMagicLinkSchema,
  requestPasswordResetSchema,
  resetPasswordSchema,
  signInWithPasswordSchema,
  totpCodeSchema,
  updateUserProfileSchema,
  userProfileFilterSchema,
} from "./auth.schema";
export type {
  CreateUserProfileInput,
  OAuthProviderIdInput,
  ReauthenticateInput,
  RegisterWithPasswordInput,
  RequestEmailVerificationInput,
  RequestMagicLinkInput,
  RequestPasswordResetInput,
  ResetPasswordInput,
  SignInWithPasswordInput,
  UpdateUserProfileInput,
  UserProfileFilterInput,
} from "./auth.schema";
export {
  ATTACHMENT_FILE_EXTENSIONS,
  ATTACHMENT_FILE_MIME_TYPES,
  ATTACHMENT_IMAGE_MIME_TYPES,
  ATTACHMENT_INLINE_MIME_TYPES,
  ATTACHMENT_TEXT_EXTENSIONS,
  ATTACHMENT_TEXT_MIME_TYPE,
  ATTACHMENT_UPLOAD_ACCEPT,
  attachmentBlurPlaceholderSchema,
  attachmentContentQuerySchema,
  attachmentDeleteResultSchema,
  attachmentDetailSchema,
  attachmentFileMimeTypeSchema,
  attachmentFilterSchema,
  attachmentImageMimeTypeSchema,
  attachmentInlineMimeTypeSchema,
  attachmentListResultSchema,
  attachmentMediaSchema,
  attachmentMediaTypeSchema,
  attachmentPageSchema,
  attachmentServableVariantSchema,
  attachmentSortFieldSchema,
  attachmentStatusSchema,
  attachmentSummarySchema,
  attachmentUploadResultSchema,
  attachmentVariantNameSchema,
  attachmentVariantProjectionSchema,
  attachmentVariantSetSchema,
  createAttachmentIntentSchema,
  MAX_ATTACHMENT_UPLOAD_BYTES,
  MAX_BLUR_DATA_URI_BYTES,
  MAX_IMAGE_UPLOAD_BYTES,
  updateAttachmentIntentSchema,
} from "./attachment.schema";
export type {
  AttachmentContentQueryInput,
  AttachmentFilterInput,
  CreateAttachmentIntentInput,
  UpdateAttachmentIntentInput,
} from "./attachment.schema";
export {
  dateRangeQuerySchema,
  explicitBooleanQuerySchema,
  idempotencyKeySchema,
  isoTimestampSchema,
  jsonValueSchema,
  paginationQuerySchema,
  progressSchema,
  sortDirectionSchema,
  sortSchema,
  tagIdsSchema,
  uuidSchema,
} from "./common.schema";
export type {
  DateRangeQueryInput,
  ExplicitBooleanQueryInput,
  IsoTimestampInput,
  JsonValueInput,
  PaginationQueryInput,
  ProgressInput,
  SortInput,
  UuidInput,
} from "./common.schema";
export { exactByteLabel, formatBinaryBytes } from "./format-bytes";
export {
  noteVersionCursorSchema,
  noteVersionDetailSchema,
  noteVersionListQuerySchema,
  noteVersionPageSchema,
  noteVersionRestoreResultSchema,
  noteVersionSummarySchema,
  restoreNoteVersionSchema,
} from "./note-version.schema";
export type { NoteVersionListQueryInput, RestoreNoteVersionInput } from "./note-version.schema";
export {
  NOTE_DOCUMENT_ATTACHMENT_CLASS,
  NOTE_DOCUMENT_ATTACHMENT_META_CLASS,
  NOTE_DOCUMENT_ATTACHMENT_NAME_CLASS,
  NOTE_DOCUMENT_ATTACHMENT_SIZE_CLASS,
  NOTE_DOCUMENT_CODE_LANGUAGES,
  NOTE_DOCUMENT_IMAGE_ALIGNMENTS,
  NOTE_DOCUMENT_IMAGE_ALIGN_DEFAULT,
  NOTE_DOCUMENT_IMAGE_CAPTION_CLASS,
  NOTE_DOCUMENT_IMAGE_CLASS,
  NOTE_DOCUMENT_IMAGE_FIGURE_CLASS,
  NOTE_DOCUMENT_IMAGE_WRAP_DEFAULT,
  NOTE_DOCUMENT_IMAGE_WRAP_MODES,
  NOTE_DOCUMENT_LIMITS,
  NOTE_DOCUMENT_MARK_TYPES,
  NOTE_DOCUMENT_MENTION_CLASS,
  NOTE_DOCUMENT_MENTION_PREFIX,
  NOTE_DOCUMENT_NODE_TYPES,
  NOTE_DOCUMENT_PAGE_BREAK_CLASS,
  NOTE_DOCUMENT_SCHEMA_VERSION,
  type NoteDocument,
  type NoteDocumentAttachmentAttrs,
  type NoteDocumentCodeLanguage,
  type NoteDocumentImageAlign,
  type NoteDocumentImageAttrs,
  type NoteDocumentImageWrap,
  type NoteDocumentJson,
  type NoteDocumentMarkType,
  type NoteDocumentMentionAttrs,
  type NoteDocumentMigrationResult,
  type NoteDocumentNodeType,
  type NoteDocumentSafeParseResult,
  NoteDocumentMigrationError,
  countChecklist,
  extractNoteContentPlain,
  migrateNoteDocument,
  normalizeNoteDocumentCodeLanguage,
  normalizeUnsupportedNodes,
  noteDocumentAttachmentAttrs,
  noteDocumentImageAttrs,
  noteDocumentMentionAttrs,
  noteDocumentSchema,
  parseNoteDocument,
  renderDocumentHtml,
  resolveNoteImageWrap,
  safeParseNoteDocument,
  sanitizeDocumentUrl,
} from "./document.schema";
export {
  copyNoteSchema,
  createFolderSchema,
  createNoteSchema,
  createNoteMetadataSchema,
  deleteFolderSchema,
  deleteNoteSchema,
  folderCreateResultSchema,
  folderDeleteResultSchema,
  folderListQuerySchema,
  folderPageSchema,
  folderSummarySchema,
  folderUpdateResultSchema,
  moveNoteSchema,
  noteCreateResultSchema,
  noteDeleteResultSchema,
  noteDetailSchema,
  noteListQuerySchema,
  noteListViewSchema,
  noteLocationSchema,
  noteMetadataFilterSchema,
  noteMoveResultSchema,
  noteNavigationItemSchema,
  noteNavigationQuerySchema,
  noteNavigationSchema,
  notePageSchema,
  notePermanentDeleteResultSchema,
  noteRestoreResultSchema,
  noteShareDeleteResultSchema,
  noteShareGrantSchema,
  noteShareListSchema,
  noteShareMutationPermissionSchema,
  noteSharePermissionSchema,
  noteShareUpsertResultSchema,
  noteSortFieldSchema,
  noteSummarySchema,
  noteTypeSchema,
  noteUpdateResultSchema,
  pageSizeSchema,
  permanentDeleteNoteSchema,
  restoreNoteSchema,
  updateFolderSchema,
  updateNoteSchema,
  updateNoteMetadataSchema,
  upsertNoteShareSchema,
} from "./note.schema";
export type {
  CopyNoteInput,
  CreateFolderInput,
  CreateNoteInput,
  CreateNoteMetadataInput,
  DeleteFolderInput,
  DeleteNoteInput,
  FolderListQueryInput,
  MoveNoteInput,
  NoteListQueryInput,
  NoteMetadataFilterInput,
  NoteNavigationQueryInput,
  PermanentDeleteNoteInput,
  RestoreNoteInput,
  UpdateFolderInput,
  UpdateNoteInput,
  UpdateNoteMetadataInput,
  UpsertNoteShareInput,
} from "./note.schema";
export {
  createProjectSchema,
  projectCoverImageUrlSchema,
  projectAccessRoleSchema,
  projectCreateResultSchema,
  projectDeleteResultSchema,
  projectDetailSchema,
  projectFilterSchema,
  projectListQuerySchema,
  projectMemberAccessSourceSchema,
  projectMemberSchema,
  projectMutationProjectSchema,
  projectPageSchema,
  projectSortFieldSchema,
  projectStatusSchema,
  projectStatusResultSchema,
  projectSummarySchema,
  projectTaskProgressSchema,
  projectUpdateResultSchema,
  updateProjectSchema,
} from "./project.schema";
export type {
  CreateProjectInput,
  ProjectFilterInput,
  ProjectListQueryInput,
  UpdateProjectInput,
} from "./project.schema";
export {
  recentSearchSchema,
  recentSearchesPayloadSchema,
  searchAvailabilitySchema,
  searchHighlightSchema,
  searchModeSchema,
  searchPageSchema,
  searchQuerySchema,
  searchResultSchema,
  searchSortDirectionSchema,
  searchSortSchema,
  searchSuggestionQuerySchema,
  searchSuggestionSchema,
} from "./search.schema";
export type {
  RecentSearchOutput,
  RecentSearchesPayloadOutput,
  SearchAvailabilityOutput,
  SearchHighlightOutput,
  SearchPageOutput,
  SearchQueryInput,
  SearchResultOutput,
  SearchSuggestionOutput,
  SearchSuggestionQueryInput,
} from "./search.schema";
export {
  notificationKindSchema,
  notificationListQuerySchema,
  notificationPageSchema,
  notificationReadResultSchema,
  notificationReadStateSchema,
  notificationsMarkAllResultSchema,
  notificationSummarySchema,
  notificationTargetTypeSchema,
  shellBootstrapSchema,
  shellBootstrapQuerySchema,
  shellWorkspaceMembershipSchema,
  workspaceSelectorSchema,
} from "./shell.schema";
export type {
  NotificationListQueryInput,
  NotificationReadStateInput,
  ShellBootstrapQueryInput,
  WorkspaceSelectorInput,
} from "./shell.schema";
export {
  createTagSchema,
  TAG_COLOR_PATTERN,
  TAG_DEFAULT_COLOR,
  tagColorSchema,
  tagCreateResultSchema,
  tagDeleteResultSchema,
  tagListQuerySchema,
  tagNameSchema,
  tagPageSchema,
  tagSortFieldSchema,
  tagSummarySchema,
  tagUpdateResultSchema,
  updateTagSchema,
} from "./tag.schema";
export type { CreateTagInput, TagListQueryInput, UpdateTagInput } from "./tag.schema";
export {
  bulkTaskSchema,
  createTaskSchema,
  createTaskStatusSchema,
  customTaskStatusListSchema,
  customTaskStatusSchema,
  reorderTaskSchema,
  TASK_BULK_MAX,
  TASK_STATUS_RESERVED_NAMES,
  taskBulkResultSchema,
  taskCreateResultSchema,
  taskCronSchema,
  taskDeleteResultSchema,
  taskDescriptionSchema,
  taskDetailSchema,
  taskGroupingSchema,
  taskListInputSchema,
  taskListQuerySchema,
  taskPageSchema,
  taskPrioritySchema,
  taskRecurrenceSchema,
  taskReorderResultSchema,
  taskSortFieldSchema,
  taskStatusColorSchema,
  taskStatusDeleteResultSchema,
  taskStatusListQuerySchema,
  taskStatusMutationResultSchema,
  taskStatusNameSchema,
  taskStatusSchema,
  taskSummarySchema,
  taskTitleSchema,
  taskUpdateResultSchema,
  updateTaskSchema,
  updateTaskStatusSchema,
} from "./task.schema";
export type {
  BulkTaskInput,
  CreateTaskInput,
  CreateTaskStatusInput,
  ReorderTaskInput,
  TaskListInput,
  TaskListQueryInput,
  TaskStatusListQueryInput,
  UpdateTaskInput,
  UpdateTaskStatusInput,
} from "./task.schema";
export {
  createWorkspaceSchema,
  acceptWorkspaceInvitationSchema,
  changeWorkspaceMemberRoleSchema,
  invitationListQuerySchema,
  invitationStatusSchema,
  invitationTokenSchema,
  inviteWorkspaceMemberSchema,
  membershipEmailSchema,
  membershipListQuerySchema,
  storageMaintenanceReportSchema,
  storageMaintenanceRequestSchema,
  storageMaintenanceSweepNameSchema,
  storageMaintenanceSweepReportSchema,
  updateWorkspaceSchema,
  workspaceCreateResultSchema,
  workspaceDeleteResultSchema,
  workspaceDeleteSchema,
  workspaceDetailSchema,
  workspaceFilterSchema,
  workspaceListQuerySchema,
  workspaceInvitationAcceptResultSchema,
  workspaceInvitationPageSchema,
  workspaceInvitationResendResultSchema,
  workspaceInvitationRevokeResultSchema,
  workspaceInvitationSummarySchema,
  workspaceInviteResultSchema,
  workspaceMemberLeaveResultSchema,
  workspaceMemberPageSchema,
  workspaceMemberRemoveResultSchema,
  workspaceMemberRoleChangeResultSchema,
  workspaceMemberSummarySchema,
  workspacePageSchema,
  workspacePlanSchema,
  workspaceRoleSchema,
  workspaceSettingsSchema,
  workspaceSortFieldSchema,
  workspaceStorageUsageSchema,
  workspaceSummarySchema,
  workspaceUpdateResultSchema,
} from "./workspace.schema";
export type {
  AcceptWorkspaceInvitationInput,
  ChangeWorkspaceMemberRoleInput,
  CreateWorkspaceInput,
  InvitationListQueryInput,
  InviteWorkspaceMemberInput,
  MembershipListQueryInput,
  StorageMaintenanceRequestInput,
  UpdateWorkspaceInput,
  WorkspaceDeleteInput,
  WorkspaceFilterInput,
  WorkspaceListQueryInput,
  WorkspaceStorageUsageOutput,
} from "./workspace.schema";
