/**
 * Stable public barrel for cross-boundary Zod schemas and inferred inputs.
 *
 * Import consumers from `@notted/shared-validators`, never package internals.
 */

export {
  authPasswordSchema,
  createUserProfileSchema,
  oauthProviderIdSchema,
  passkeyNameSchema,
  reauthenticateSchema,
  recoveryCodeSchema,
  registerWithPasswordSchema,
  requestEmailVerificationSchema,
  requestMagicLinkSchema,
  requestPasswordResetSchema,
  resetPasswordSchema,
  signInWithPasswordSchema,
  totpCodeSchema,
  updateUserProfileSchema,
  userProfileFilterSchema,
} from "./auth.schema";
export type {
  CreateUserProfileInput,
  OAuthProviderIdInput,
  ReauthenticateInput,
  RegisterWithPasswordInput,
  RequestEmailVerificationInput,
  RequestMagicLinkInput,
  RequestPasswordResetInput,
  ResetPasswordInput,
  SignInWithPasswordInput,
  UpdateUserProfileInput,
  UserProfileFilterInput,
} from "./auth.schema";
export {
  attachmentFilterSchema,
  attachmentSortFieldSchema,
  attachmentStatusSchema,
  createAttachmentIntentSchema,
  updateAttachmentIntentSchema,
} from "./attachment.schema";
export type {
  AttachmentFilterInput,
  CreateAttachmentIntentInput,
  UpdateAttachmentIntentInput,
} from "./attachment.schema";
export {
  dateRangeQuerySchema,
  explicitBooleanQuerySchema,
  idempotencyKeySchema,
  isoTimestampSchema,
  jsonValueSchema,
  paginationQuerySchema,
  sortDirectionSchema,
  sortSchema,
  uuidSchema,
} from "./common.schema";
export type {
  DateRangeQueryInput,
  ExplicitBooleanQueryInput,
  IsoTimestampInput,
  JsonValueInput,
  PaginationQueryInput,
  SortInput,
  UuidInput,
} from "./common.schema";
export {
  NOTE_DOCUMENT_LIMITS,
  NOTE_DOCUMENT_MARK_TYPES,
  NOTE_DOCUMENT_NODE_TYPES,
  NOTE_DOCUMENT_SCHEMA_VERSION,
  type NoteDocument,
  type NoteDocumentJson,
  type NoteDocumentMarkType,
  type NoteDocumentMigrationResult,
  type NoteDocumentNodeType,
  type NoteDocumentSafeParseResult,
  NoteDocumentMigrationError,
  extractNoteContentPlain,
  migrateNoteDocument,
  normalizeUnsupportedNodes,
  noteDocumentSchema,
  parseNoteDocument,
  renderDocumentHtml,
  safeParseNoteDocument,
  sanitizeDocumentUrl,
} from "./document.schema";
export {
  createFolderSchema,
  createNoteSchema,
  createNoteMetadataSchema,
  deleteFolderSchema,
  deleteNoteSchema,
  folderCreateResultSchema,
  folderDeleteResultSchema,
  folderListQuerySchema,
  folderPageSchema,
  folderSummarySchema,
  folderUpdateResultSchema,
  moveNoteSchema,
  noteCreateResultSchema,
  noteDeleteResultSchema,
  noteDetailSchema,
  noteListQuerySchema,
  noteListViewSchema,
  noteLocationSchema,
  noteMetadataFilterSchema,
  noteMoveResultSchema,
  noteNavigationItemSchema,
  noteNavigationQuerySchema,
  noteNavigationSchema,
  notePageSchema,
  notePermanentDeleteResultSchema,
  noteRestoreResultSchema,
  noteShareDeleteResultSchema,
  noteShareGrantSchema,
  noteShareListSchema,
  noteShareMutationPermissionSchema,
  noteSharePermissionSchema,
  noteShareUpsertResultSchema,
  noteSortFieldSchema,
  noteSummarySchema,
  noteTypeSchema,
  noteUpdateResultSchema,
  pageSizeSchema,
  permanentDeleteNoteSchema,
  restoreNoteSchema,
  updateFolderSchema,
  updateNoteSchema,
  updateNoteMetadataSchema,
  upsertNoteShareSchema,
} from "./note.schema";
export type {
  CreateFolderInput,
  CreateNoteInput,
  CreateNoteMetadataInput,
  DeleteFolderInput,
  DeleteNoteInput,
  FolderListQueryInput,
  MoveNoteInput,
  NoteListQueryInput,
  NoteMetadataFilterInput,
  NoteNavigationQueryInput,
  PermanentDeleteNoteInput,
  RestoreNoteInput,
  UpdateFolderInput,
  UpdateNoteInput,
  UpdateNoteMetadataInput,
  UpsertNoteShareInput,
} from "./note.schema";
export {
  createProjectSchema,
  projectCoverImageUrlSchema,
  projectAccessRoleSchema,
  projectCreateResultSchema,
  projectDeleteResultSchema,
  projectDetailSchema,
  projectFilterSchema,
  projectListQuerySchema,
  projectMemberAccessSourceSchema,
  projectMemberSchema,
  projectMutationProjectSchema,
  projectPageSchema,
  projectSortFieldSchema,
  projectStatusSchema,
  projectStatusResultSchema,
  projectSummarySchema,
  projectTaskProgressSchema,
  projectUpdateResultSchema,
  updateProjectSchema,
} from "./project.schema";
export type {
  CreateProjectInput,
  ProjectFilterInput,
  ProjectListQueryInput,
  UpdateProjectInput,
} from "./project.schema";
export { searchModeSchema, searchQuerySchema, searchSortSchema } from "./search.schema";
export type { SearchQueryInput } from "./search.schema";
export {
  notificationKindSchema,
  notificationListQuerySchema,
  notificationPageSchema,
  notificationReadResultSchema,
  notificationReadStateSchema,
  notificationsMarkAllResultSchema,
  notificationSummarySchema,
  notificationTargetTypeSchema,
  shellBootstrapSchema,
  shellBootstrapQuerySchema,
  shellWorkspaceMembershipSchema,
  workspaceSelectorSchema,
} from "./shell.schema";
export type {
  NotificationListQueryInput,
  NotificationReadStateInput,
  ShellBootstrapQueryInput,
  WorkspaceSelectorInput,
} from "./shell.schema";
export {
  createTaskSchema,
  taskFilterSchema,
  taskPrioritySchema,
  taskRecurrenceSchema,
  taskSortFieldSchema,
  taskStatusSchema,
  updateTaskSchema,
} from "./task.schema";
export type { CreateTaskInput, TaskFilterInput, UpdateTaskInput } from "./task.schema";
export {
  createWorkspaceSchema,
  acceptWorkspaceInvitationSchema,
  changeWorkspaceMemberRoleSchema,
  invitationListQuerySchema,
  invitationStatusSchema,
  invitationTokenSchema,
  inviteWorkspaceMemberSchema,
  membershipEmailSchema,
  membershipListQuerySchema,
  updateWorkspaceSchema,
  workspaceCreateResultSchema,
  workspaceDeleteResultSchema,
  workspaceDeleteSchema,
  workspaceDetailSchema,
  workspaceFilterSchema,
  workspaceListQuerySchema,
  workspaceInvitationAcceptResultSchema,
  workspaceInvitationPageSchema,
  workspaceInvitationResendResultSchema,
  workspaceInvitationRevokeResultSchema,
  workspaceInvitationSummarySchema,
  workspaceInviteResultSchema,
  workspaceMemberLeaveResultSchema,
  workspaceMemberPageSchema,
  workspaceMemberRemoveResultSchema,
  workspaceMemberRoleChangeResultSchema,
  workspaceMemberSummarySchema,
  workspacePageSchema,
  workspacePlanSchema,
  workspaceRoleSchema,
  workspaceSettingsSchema,
  workspaceSortFieldSchema,
  workspaceSummarySchema,
  workspaceUpdateResultSchema,
} from "./workspace.schema";
export type {
  AcceptWorkspaceInvitationInput,
  ChangeWorkspaceMemberRoleInput,
  CreateWorkspaceInput,
  InvitationListQueryInput,
  InviteWorkspaceMemberInput,
  MembershipListQueryInput,
  UpdateWorkspaceInput,
  WorkspaceDeleteInput,
  WorkspaceFilterInput,
  WorkspaceListQueryInput,
} from "./workspace.schema";
